apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kstone-etcd-operator-mutating-admission
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnekNDQW11Z0F3SUJBZ0lVRTFRcmYwYmZvZU9pdnFSL2w4ZldsTVI1cmdBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VURUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtkRU1Rc3dDUVlEVlFRSERBSlRXakVQTUEwRwpBMVVFQ2d3R1MzTjBiMjVsTVJjd0ZRWURWUVFEREE1TGMzUnZibVVnVW05dmRDQkRRVEFlRncweU1qQTBNVFV4Ck1ESXdNRFphRncwek1qQTBNVEl4TURJd01EWmFNRkV4Q3pBSkJnTlZCQVlUQWtOT01Rc3dDUVlEVlFRSURBSkgKUkRFTE1Ba0dBMVVFQnd3Q1Uxb3hEekFOQmdOVkJBb01Ca3R6ZEc5dVpURVhNQlVHQTFVRUF3d09TM04wYjI1bApJRkp2YjNRZ1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNEpMTzhDaGxvClMwMWpudGNrenJhR1NYZTlVSE1FR3M3SEJPU0xvT3VQd3FsRmFoUGRiR1ZTU0t5a2pLUFJRLzQ4UHVUUHp1VmkKNi9GNytSY2VWMHdUUUdNdkxBdE90TUQrclhZRTlsNGtEN041aWxvMTJFRTdnNDhpZDFqbHFIUWY0RWh4QkhqUwp5TWFaSHltZEp0N0t6NWhFQW5IY3o4RWhMZ3RpNWxqY1ROak9Sd2h4M1MwWU9FTjdWSExKeUUwRGdpYWdhZnh3CjhBakE4MWM1MGdUYmxDeWszUEdCQm5FNHg0Y2JqNmt3SVlwNXY2RE9GUHE0RGd2Tm5jR1FVS3NHWWE5aFp0MDYKSHA1TDgyUUhZRlM2UjlEVGR0QzJtM0x4dzZ0V3hBSmIxOEV2QkVrMXducHdWdEc2WVBFOHFBMnI1ZmV5UDZlegoyakpWc095MSs5L2hBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlRVUy9nbWRKcnNYeVZRQ1NwTTk5QU05Rm9oCmtUQWZCZ05WSFNNRUdEQVdnQlRVUy9nbWRKcnNYeVZRQ1NwTTk5QU05Rm9oa1RBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTEybVkzMTdSSnZ0R3FrcC9zUHdvdjZzYVNVbThSRndNWQpHdTk1VUsyMkRCOHIrNC9zcWtteERKTHNDbHB0ZUZBY3Y1QkszdzhRcXpKQlR1cDVWMUdnMWZkZk04bkFlUDZWCllXa0tJZGk1RXF0bWJsTlZSNkYzWEFxODUvcnltaW5MdlV0VEhpcUdhbTZ0dk1sWHZPOHc0Z3hwNS9Kdmt5bkYKZFVGMloyaEVmSGw3T3gzWGhrOVBoNEI3MEIrTUVBU0dHd1RBaXduQThVN3RBZEgzeHc0NGlTZGt2NXBMbGtZQgoxTDZCVzNWbVg2RjJiNkRlSWoyVmVGT0FEVndLa2hPVkRFVTVSQm9zTVYrem0vMTRabnVIOVprR0dtSXBDVTFXCmZWdFZxbnVXUE1hSWJ3UlY3ZVg1WlFaaVBFRFJPZzg2cVJQdit6Z1g3WExITHp0VEpCQWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
      service:
        name: kstone-etcd-operator
        namespace: {{ .Release.Namespace }}
        path: "/mutating-etcd"
    failurePolicy: Fail
    name: {{ include "etcd-operator.fullname" . }}.{{ .Release.Namespace }}.svc
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    rules:
      - apiGroups: [ "etcd.tkestack.io" ]
        apiVersions: [ "v1alpha1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "etcdclusters" ]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kstone-etcd-operator-validating-admission
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnekNDQW11Z0F3SUJBZ0lVRTFRcmYwYmZvZU9pdnFSL2w4ZldsTVI1cmdBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VURUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtkRU1Rc3dDUVlEVlFRSERBSlRXakVQTUEwRwpBMVVFQ2d3R1MzTjBiMjVsTVJjd0ZRWURWUVFEREE1TGMzUnZibVVnVW05dmRDQkRRVEFlRncweU1qQTBNVFV4Ck1ESXdNRFphRncwek1qQTBNVEl4TURJd01EWmFNRkV4Q3pBSkJnTlZCQVlUQWtOT01Rc3dDUVlEVlFRSURBSkgKUkRFTE1Ba0dBMVVFQnd3Q1Uxb3hEekFOQmdOVkJBb01Ca3R6ZEc5dVpURVhNQlVHQTFVRUF3d09TM04wYjI1bApJRkp2YjNRZ1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDNEpMTzhDaGxvClMwMWpudGNrenJhR1NYZTlVSE1FR3M3SEJPU0xvT3VQd3FsRmFoUGRiR1ZTU0t5a2pLUFJRLzQ4UHVUUHp1VmkKNi9GNytSY2VWMHdUUUdNdkxBdE90TUQrclhZRTlsNGtEN041aWxvMTJFRTdnNDhpZDFqbHFIUWY0RWh4QkhqUwp5TWFaSHltZEp0N0t6NWhFQW5IY3o4RWhMZ3RpNWxqY1ROak9Sd2h4M1MwWU9FTjdWSExKeUUwRGdpYWdhZnh3CjhBakE4MWM1MGdUYmxDeWszUEdCQm5FNHg0Y2JqNmt3SVlwNXY2RE9GUHE0RGd2Tm5jR1FVS3NHWWE5aFp0MDYKSHA1TDgyUUhZRlM2UjlEVGR0QzJtM0x4dzZ0V3hBSmIxOEV2QkVrMXducHdWdEc2WVBFOHFBMnI1ZmV5UDZlegoyakpWc095MSs5L2hBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlRVUy9nbWRKcnNYeVZRQ1NwTTk5QU05Rm9oCmtUQWZCZ05WSFNNRUdEQVdnQlRVUy9nbWRKcnNYeVZRQ1NwTTk5QU05Rm9oa1RBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTEybVkzMTdSSnZ0R3FrcC9zUHdvdjZzYVNVbThSRndNWQpHdTk1VUsyMkRCOHIrNC9zcWtteERKTHNDbHB0ZUZBY3Y1QkszdzhRcXpKQlR1cDVWMUdnMWZkZk04bkFlUDZWCllXa0tJZGk1RXF0bWJsTlZSNkYzWEFxODUvcnltaW5MdlV0VEhpcUdhbTZ0dk1sWHZPOHc0Z3hwNS9Kdmt5bkYKZFVGMloyaEVmSGw3T3gzWGhrOVBoNEI3MEIrTUVBU0dHd1RBaXduQThVN3RBZEgzeHc0NGlTZGt2NXBMbGtZQgoxTDZCVzNWbVg2RjJiNkRlSWoyVmVGT0FEVndLa2hPVkRFVTVSQm9zTVYrem0vMTRabnVIOVprR0dtSXBDVTFXCmZWdFZxbnVXUE1hSWJ3UlY3ZVg1WlFaaVBFRFJPZzg2cVJQdit6Z1g3WExITHp0VEpCQWYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
      service:
        name: kstone-etcd-operator
        namespace: {{ .Release.Namespace }}
        path: "/validating-etcd"
    failurePolicy: Fail
    name: {{ include "etcd-operator.fullname" . }}.{{ .Release.Namespace }}.svc
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    rules:
      - apiGroups: [ "etcd.tkestack.io" ]
        apiVersions: [ "v1alpha1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "etcdclusters" ]