apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstone-etcdcluster-controller
  namespace: kstone
  labels:
    app: kstone-etcdcluster-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstone-etcdcluster-controller
  template:
    metadata:
      labels:
        app: kstone-etcdcluster-controller
    spec:
      serviceAccountName: kstone-controller
      volumes:
        - name: kstone-kubeconfig
          secret:
            secretName: kstone-kubeconfig
      containers:
        - name: kstone-etcdcluster-controller
          image: mirrors.tencent.com/etcd/kstone-controller:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: kstone-kubeconfig
              mountPath: "/etc/kstone/config/kubeconfig"
              readOnly: true
          args:
            - etcdcluster
            - --kubeconfig
            - /etc/kstone/config/kubeconfig/default.yaml
          command:
            - /data/app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstone-etcdinspection-controller
  namespace: kstone
  labels:
    app: kstone-etcdinspection-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstone-etcdinspection-controller
  template:
    metadata:
      labels:
        app: kstone-etcdinspection-controller
    spec:
      serviceAccountName: kstone-controller
      volumes:
        - name: kstone-kubeconfig
          secret:
            secretName: kstone-kubeconfig
      containers:
        - name: kstone-etcdinspection-controller
          image: mirrors.tencent.com/etcd/kstone-controller:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: kstone-kubeconfig
              mountPath: "/etc/kstone/config/kubeconfig"
              readOnly: true
          args:
            - etcdmonitor
            - --kubeconfig
            - /etc/kstone/config/kubeconfig/default.yaml
          command:
            - /data/app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kstone-controller
  namespace: kstone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kstone-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kstone-controller
    namespace: kstone