{
 "title": "Kstone",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "job",
    "label": "etcd",
    "query": {
     "query": "query_result(sum by (job) (increase(etcd_server_has_leader{}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\"}[5m])) by (job, endpoint, grpc_method, instance) > 0",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}_{{grpc_method}} "
    }
   ]
  },
  {
   "title": "RPC Increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"$job\"}[2m])) by (job, endpoint, grpc_method, instance) ",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}_{{grpc_method}} "
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "DB Usage Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{job=\"$job\"}/etcd_server_quota_backend_bytes{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"$job\"}[5m])) by (job,instance,endpoint,le))",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"$job\"}[5m])) by (job, instance,endpoint,le))",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}  DB fsync"
    }
   ]
  },
  {
   "title": "The total number of wathcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_watcher_total{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}_mvcc_watcher_total"
    }
   ]
  },
  {
   "title": "Disk Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{job=\"$job\"}[5m]) > 0) by (remark,instance,le,grpc_method,endpoint))",
     "legendFormat": "commit_spil_{{remark}}_{{instance}}_{{endpoint}}_{{grpc_method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{job=\"$job\"}[5m]) > 0) by (remark,instance,le,grpc_method,endpoint))",
     "legendFormat": "commit_rebalance_{{remark}}_{{instance}}_{{endpoint}}_{{grpc_method}}"
    }
   ]
  },
  {
   "title": "The total number of pending events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_pending_events_total{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"$job\"}[1m])",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "The total number of key",
   "type": "graph",
   "description": "etcd_debugging_mvcc_keys_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}} Proposal Failed Total"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"$job\"}) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}  Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}  Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}  Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{job=\"$job\"}[6h]) ",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "etcd GRPC Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\", grpc_method=~\"Range|Txn\"}[5m]) > 0) by (remark,instance,le,grpc_method,endpoint))",
     "legendFormat": "{{remark}}_{{instance}}_{{endpoint}}_{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Proposals Pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{job=\"$job\"}) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}} Proposals pending"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}} total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"$job\"}[5m])) by (job,instance)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}   total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "The total number of slow apply",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "{{remark}}_{{etcdResourceName}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "The total number of slow watcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_slow_watcher_total{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Disks Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum{job=\"$job\"}[1m]))  by (job) ",
     "legendFormat": "{{job}}\tThe latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum{job=\"$job\"}[1m]))  by (job) ",
     "legendFormat": "{{job}} The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Auth Revison Increase",
   "type": "graph",
   "description": "auth revision increase",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "count/5m" }
   ],
   "targets": [
    {
     "expr": "increase(etcd_debugging_auth_revision{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Auth Revison",
   "type": "graph",
   "description": "Auth Revision",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_auth_revision{job=\"$job\"}",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{job=\"$job\"}[1m])) by (job)",
     "legendFormat": "{{job}} The total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "ETCD V2 HTTP QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_http_received_total{job=\"$job\"}[5m])) by (method,instance,job)",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}_{{method}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{job=\"$job\"}[1m]))  by (job) ",
     "legendFormat": "{{job}}  The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{job=\"$job\"}[1m]))  by (job) ",
     "legendFormat": "{{job}}  The total number of bytes sent to grpc clients"
    }
   ]
  },
  {
   "title": "ETCD V2 HTTP Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_http_successful_duration_seconds_bucket{job=\"$job\"}[5m]) ) by (job,instance,method,le))",
     "legendFormat": "{{job}}_{{instance}}_{{endpoint}}_{{method}}"
    }
   ]
  },
  { "title": "Kstone Inspection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "The number of healthy/unhealthy endpoint",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kstone_inspection_etcd_endpoint_healthy{clusterName=\"$job\"})",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(kstone_inspection_etcd_endpoint_healthy{clusterName=\"$job\"} == 0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "The total number of resource key",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum by (clusterName,etcdPrefix,resourceName) (kstone_inspection_etcd_key_total{clusterName=\"$job\"}))",
     "legendFormat": "{{etcdPrefix}}_{{resourceName}}"
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kstone_inspection_etcd_endpoint_alarm{clusterName=\"$job\"}",
     "legendFormat": "{{clusterName}}-{{alarmType}}-{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "The consistency difference between each node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kstone_inspection_etcd_node_diff_total{clusterName=\"$job\"}",
     "legendFormat": "key_{{clusterName}}"
    },
    {
     "expr": "kstone_inspection_etcd_node_revision_diff_total{clusterName=\"$job\"}",
     "legendFormat": "revision_{{clusterName}}"
    },
    {
     "expr": "kstone_inspection_etcd_node_index_diff_total{clusterName=\"$job\"}",
     "legendFormat": "index_{{clusterName}}"
    },
    {
     "expr": "kstone_inspection_etcd_node_raft_applied_index_diff_total{clusterName=\"$job\"}",
     "legendFormat": "raft_applied_{{clusterName}}"
    },
    {
     "expr": "kstone_inspection_etcd_node_raft_index_diff_total{clusterName=\"$job\"}",
     "legendFormat": "raft_index_{{clusterName}}"
    }
   ]
  },
  {
   "title": "Hot Write QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(15, sum(rate(kstone_inspection_etcd_request_total{clusterName=\"$job\"}[5m])) by (clusterName,etcdPrefix,grpcMethod,resourceName))",
     "legendFormat": "{{etcdPrefix}}_{{grpcMethod}}_{{resourceName}}"
    }
   ]
  }
 ]
}