# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.0.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
#  fsGroup: 472
  runAsGroup: 472
  runAsUser: 472

service:
  type: NodePort
  port: 80

prodResources:
  limits:
    cpu: 2
    memory: 4G
  requests:
    cpu: 500m
    memory: 512Mi

testResources:
  limits:
    cpu: 1
    memory: 2G
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccountName: kstone
