name: e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: ${{ github.sha }}
  SCRIPTS_DIR: test/scripts
  E2E_KUBECONFIG_PATH: test/fixtures/config
  FIXTURES_DIR: test/fixtures/manifests

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.KSTONE_REGISTRY_USERNAME }}
        password: ${{ secrets.KSTONE_REGISTRY_PASSWORD }}
    - name: Push Image
      run: make push
    - name: Prepare envrionment
      run: bash ${SCRIPTS_DIR}/pre.sh
    - name: Install Minikube
      run: bash ${SCRIPTS_DIR}/minikube.sh start
    - name: Install kstone
      run: bash ${SCRIPTS_DIR}/kstone.sh
    - name: e2e test
      run: make e2e
